---
title: "BogBase Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  revealjs::revealjs_presentation:
    css: slide.css
    theme: simple
    transition: fade
    background_transition: fade
---

```{r setup, include=FALSE}
library(config)
library(rpostgis)
library(huxtable)
library(dplyr)
library(plotly)
library(tmap)
library(sf)
library(kableExtra)

getSQL <- function(filepath){
    con = file(filepath, "r")
    sql.string <- ""
    
    while (TRUE){
        line <- readLines(con, n = 1)
        
        if ( length(line) == 0 ){
            break
        }
        
        line <- gsub("\\t", " ", line)
        
        if(grepl("--",line) == TRUE){
            line <- paste(sub("--","/*",line),"*/")
        }
        
        sql.string <- paste(sql.string, line)
    }
    
    close(con)
    return(sql.string)
}

# Set up connections to GeoPackage and BogBase

config <- config::get()

bogbase_con <- function() {
    
    con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(), host = config$bb_db$host, dbname = config$bb_db$dbname, user = Sys.info()[["user"]])
    
    return(con)
}

bogbase_con <- bogbase_con()
```

```{r assets, message=FALSE, warning=FALSE, include=FALSE}

site_peat_units <- st_read(bogbase_con, query='SELECT site_name, estate_name, geom FROM site_peat_units LEFT JOIN reference.ref_estates USING (estate_id)')
unit_status <- st_read(bogbase_con, query='SELECT site_name, full_desc, geom FROM reporting.vw_unit_status_max')

rename(unit_status, "Site" = site_name, "Max progress to date"= full_desc)


tm <- tm_shape(site_peat_units) + tm_fill(col='brown') + tm_layout(frame = FALSE, bg.color = "transparent", outer.margins = 0.2)
tm1 <- tm_basemap(leaflet::providers$OpenStreetMap) + tm_shape(unit_status) + tm_polygons(id="Site", col = "full_desc", title = "Site progress")

tmap_save(tm, "assets/img/site_peat_units.png", dpi = 600)
tmap_save(tm1, "assets/maps/tm1.html")
```

# Summary statement {data-transition="slide-in fade-out" .el-selection}

```{r peaty_intro, echo=FALSE, results='asis'}
peaty_area <- dbGetQuery(bogbase_con, "SELECT * FROM reporting.peaty_area WHERE region_name IS NOT NULL;")

surveyed_area <- sum(peaty_area$surveyed_ha, na.rm = TRUE)
surveyed_n <- sum(peaty_area$site_surveyed_count)
units_area <- sum(peaty_area$site_area_ha)
surveyed_perc <- (surveyed_area/units_area)*100
peat_area <- sum(peaty_area$peaty_area_ha)
peat_area_deep <- sum(peaty_area$peaty_area_40_ha)
c_tonnes <- sum(peaty_area$tonnes_carbon)
c_tonnes_per_ha <- mean(peaty_area$tonnes_carbon_per_ha)

cat(paste0('*To date, YPP has surveyed over **',format(round(surveyed_area,0),big.mark=",", trim=TRUE),' ha** of peatland on **',surveyed_n,'** unique sites. With an estimated total of **',format(round(units_area,0),big.mark=",", trim=TRUE),' ha** of peat units to investigate in our project area, YPP has surveyed **',round(surveyed_perc,0),'%** of the area so far. Based on previous surveys, YPP estimates that by the time we survey all **', format(round(units_area,0),big.mark=",", trim=TRUE),' ha**, we expect **',format(round(peat_area,0),big.mark=",", trim=TRUE),'**ha to be actual peaty soils with **',format(round(peat_area_deep,0),big.mark=",", trim=TRUE),' ha** classed as deep peat (&ge;40cm). We estimate that, all peaty soils within our project area have locked away a huge **',format(round(c_tonnes,0),big.mark=",", trim=TRUE) ,' tonnes of carbon** which gives an average of **',format(round(c_tonnes_per_ha,0),big.mark=",", trim=TRUE),' tonnes of carbon** per hectare - one of the densest terrestrial carbon stores of any habitat!*'))

```

# Mose recently surveyed sites {data-transition="slide-in fade-out"}

```{r table-test, echo=FALSE}
t1 <- dbGetQuery(bogbase_con, "SELECT site_name, to_char(survey_date_complete, 'dd Mon YYYY') survey_complete
FROM surveys LEFT JOIN site_peat_units USING (site_id) ORDER BY survey_date_complete desc LIMIT 5;")
colnames(t1) <- c("Site", "Survey completion date")
huxtable(t1) %>% theme_plain() %>% set_width(0.8)

#{data-background-iframe="assets/maps/tm1.html" style="scale:0"}
```

# {data-background="assets/img/site_peat_units.png" data-background-size="contain"}

# {data-background-iframe="assets/maps/tm1.html"}

# Erosion feature restoration {data-transition="slide-in fade-out" .el-selection}

```{r plotly, echo=FALSE, warning=FALSE, out.width="100%"}
rp_len <- dbGetQuery(bogbase_con, "SELECT * FROM reporting.restoration_cumulative_works_length_bar")
rp_len$feature <- factor(rp_len$feature, levels = c('Hag', 'Gully', 'Grip'))

ggplotly(ggplot(rp_len, aes(fill=feature, y=cum_len_km, x=works_month, text = sprintf('%s: %s km', feature, round(cum_len_km,0)))) +
    geom_bar(position="stack", stat="identity") + labs(title = 'Erosion features restored', x = 'Date', y='Cumulative length (km)', fill = "") +
    scale_fill_manual(values = c("#D4351C", "#FFDD00", "#5694CA")) + theme_classic())
```

```{r message=TRUE, warning=FALSE, include=FALSE}
dbDisconnect(bogbase_con)
```

